# azure-pipelines.yml
trigger: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: template task pat

stages:
  - template: azdo-branch-management.yaml
    parameters:
      RepoName: 'rabo-test'
      failOnError: true